version: "3.8"
services:
  app:
    container_name: vending-machine-api
    build:
      context: ./vending-machine-api
    image: ${DOCKER_IMAGE_NAME:-vending-machine-api:local}
    environment:
      - SPRING_PROFILES_ACTIVE=cicd
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      - db

  api.tests:
    container_name: vending-machine-api-tests
    build:
      context: ./vending-machine-api-tests
    image: vending-machine-api-tests:${BUILD_NUMBER:-local}
    depends_on:
      - db
      - app

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MZcwq9mXSd3XGxcJ
      - POSTGRES_DB=vending
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
      - postgres_data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
